KTX_EXEC := ~\Documents\GraphicsProjects\KTX-Software\build\Debug\toktx

IMAGES := $(shell find . -type f -name '*.png')

TEXTURES := $(IMAGES:%_BaseColor.png)

%.ktx2: %.png
	$(KTX_EXEC) --t2 --target_type RGBA --genmipmap $@ $<

.PHONY: clean
clean:
	rm -rf *.ktx2