use std::{fs, path::{self, Path, PathBuf}, str::FromStr};

use crate::gltf_loader::{GltfDocument};

#[cfg(target_os = "linux")]
const PATHS: &[&str] = &[
"ABeautifulGame/glTF/ABeautifulGame.gltf",
"AlphaBlendModeTest/glTF/AlphaBlendModeTest.gltf",
// "AnimatedColorsCube/glTF/AnimatedColorsCube.gltf", // KHR_animation_pointer
"AnimatedCube/glTF/AnimatedCube.gltf",
"AnimatedMorphCube/glTF/AnimatedMorphCube.gltf",
"AnimatedMorphCube/glTF-Quantized/AnimatedMorphCube.gltf",
"AnimatedTriangle/glTF/AnimatedTriangle.gltf",
// "AnimationPointerUVs/glTF/AnimationPointerUVs.gltf", // KHR_animation_pointer
"AnisotropyBarnLamp/glTF/AnisotropyBarnLamp.gltf",
"AnisotropyBarnLamp/glTF-KTX-BasisU/AnisotropyBarnLamp.gltf",
"AnisotropyDiscTest/glTF/AnisotropyDiscTest.gltf",
"AnisotropyRotationTest/glTF/AnisotropyRotationTest.gltf",
"AnisotropyStrengthTest/glTF/AnisotropyStrengthTest.gltf",
"AntiqueCamera/glTF/AntiqueCamera.gltf",
"AttenuationTest/glTF/AttenuationTest.gltf",
"Avocado/glTF/Avocado.gltf",
"Avocado/glTF-Draco/Avocado.gltf",
"Avocado/glTF-Quantized/Avocado.gltf",
"BarramundiFish/glTF/BarramundiFish.gltf",
"BarramundiFish/glTF-Draco/BarramundiFish.gltf",
"BoomBox/glTF/BoomBox.gltf",
"BoomBox/glTF-Draco/BoomBox.gltf",
"BoomBoxWithAxes/glTF/BoomBoxWithAxes.gltf",
"Box/glTF/Box.gltf",
"Box/glTF-Draco/Box.gltf",
"Box/glTF-Embedded/Box.gltf",
"Box With Spaces/glTF/Box With Spaces.gltf",
"BoxAnimated/glTF/BoxAnimated.gltf",
"BoxAnimated/glTF-Embedded/BoxAnimated.gltf",
"BoxInterleaved/glTF/BoxInterleaved.gltf",
"BoxInterleaved/glTF-Embedded/BoxInterleaved.gltf",
"BoxTextured/glTF/BoxTextured.gltf",
"BoxTextured/glTF-Embedded/BoxTextured.gltf",
"BoxTexturedNonPowerOfTwo/glTF/BoxTexturedNonPowerOfTwo.gltf",
"BoxTexturedNonPowerOfTwo/glTF-Embedded/BoxTexturedNonPowerOfTwo.gltf",
"BoxVertexColors/glTF/BoxVertexColors.gltf",
"BoxVertexColors/glTF-Embedded/BoxVertexColors.gltf",
"BrainStem/glTF/BrainStem.gltf",
"BrainStem/glTF-Draco/BrainStem.gltf",
"BrainStem/glTF-Embedded/BrainStem.gltf",
"BrainStem/glTF-Meshopt/BrainStem.gltf",
"BrainStem/glTF-Meshopt-EXT/BrainStem.gltf",
"Cameras/glTF/Cameras.gltf",
"Cameras/glTF-Embedded/Cameras.gltf",
"CarConcept/glTF/CarConcept.gltf",
"CarConcept/glTF-JPG/CarConcept.gltf",
"CarConcept/glTF-KTX-BasisU-Draco/CarConcept.gltf",
"CarConcept/glTF-WEBP/CarConcept.gltf",
"CarbonFibre/glTF/CarbonFibre.gltf",
"CesiumMan/glTF/CesiumMan.gltf",
"CesiumMan/glTF-Draco/CesiumMan.gltf",
"CesiumMan/glTF-Embedded/CesiumMan.gltf",
"CesiumMilkTruck/glTF/CesiumMilkTruck.gltf",
"CesiumMilkTruck/glTF-Draco/CesiumMilkTruck.gltf",
"CesiumMilkTruck/glTF-Embedded/CesiumMilkTruck.gltf",
"ChairDamaskPurplegold/glTF/ChairDamaskPurplegold.gltf",
"ChronographWatch/glTF/ChronographWatch.gltf",
"ChronographWatch/glTF-KTX-BasisU/ChronographWatch.gltf",
"ChronographWatch/glTF-WEBP/ChronographWatch.gltf",
"ClearCoatCarPaint/glTF/ClearCoatCarPaint.gltf",
"ClearCoatTest/glTF/ClearCoatTest.gltf",
"ClearcoatWicker/glTF/ClearcoatWicker.gltf",
"CommercialRefrigerator/glTF/CommercialRefrigerator.gltf",
"CompareAlphaCoverage/glTF/CompareAlphaCoverage.gltf",
"CompareAmbientOcclusion/glTF/CompareAmbientOcclusion.gltf",
"CompareAnisotropy/glTF/CompareAnisotropy.gltf",
"CompareBaseColor/glTF/CompareBaseColor.gltf",
"CompareClearcoat/glTF/CompareClearcoat.gltf",
"CompareDispersion/glTF/CompareDispersion.gltf",
"CompareEmissiveStrength/glTF/CompareEmissiveStrength.gltf",
"CompareIor/glTF/CompareIor.gltf",
"CompareIridescence/glTF/CompareIridescence.gltf",
"CompareMetallic/glTF/CompareMetallic.gltf",
"CompareNormal/glTF/CompareNormal.gltf",
"CompareRoughness/glTF/CompareRoughness.gltf",
"CompareSheen/glTF/CompareSheen.gltf",
"CompareSpecular/glTF/CompareSpecular.gltf",
"CompareTransmission/glTF/CompareTransmission.gltf",
"CompareVolume/glTF/CompareVolume.gltf",
"Corset/glTF/Corset.gltf",
"Corset/glTF-Draco/Corset.gltf",
"Cube/glTF/Cube.gltf",
// "CubeVisibility/glTF/CubeVisibility.gltf", // KHR_animation_pointer
"DamagedHelmet/glTF/DamagedHelmet.gltf",
"DamagedHelmet/glTF-Embedded/DamagedHelmet.gltf",
"DiffuseTransmissionPlant/glTF/DiffuseTransmissionPlant.gltf",
"DiffuseTransmissionTeacup/glTF/DiffuseTransmissionTeacup.gltf",
"DiffuseTransmissionTest/glTF/DiffuseTransmissionTest.gltf",
"DirectionalLight/glTF/DirectionalLight.gltf",
"DispersionTest/glTF/DispersionTest.gltf",
"DragonAttenuation/glTF/DragonAttenuation.gltf",
"DragonAttenuation/glTF-Meshopt/DragonAttenuation.gltf",
"DragonAttenuation/glTF-Meshopt-EXT/DragonAttenuation.gltf",
"DragonDispersion/glTF/DragonDispersion.gltf",
"Duck/glTF/Duck.gltf",
"Duck/glTF-Draco/Duck.gltf",
"Duck/glTF-Embedded/Duck.gltf",
"Duck/glTF-Quantized/Duck.gltf",
"EmissiveStrengthTest/glTF/EmissiveStrengthTest.gltf",
"EnvironmentTest/glTF/EnvironmentTest.gltf",
"FlightHelmet/glTF/FlightHelmet.gltf",
"Fox/glTF/Fox.gltf",
"GlamVelvetSofa/glTF/GlamVelvetSofa.gltf",
"GlassBrokenWindow/glTF/GlassBrokenWindow.gltf",
"GlassHurricaneCandleHolder/glTF/GlassHurricaneCandleHolder.gltf",
"GlassVaseFlowers/glTF/GlassVaseFlowers.gltf",
"IORTestGrid/glTF/IORTestGrid.gltf",
"InterpolationTest/glTF/InterpolationTest.gltf",
"IridescenceAbalone/glTF/IridescenceAbalone.gltf",
"IridescenceDielectricSpheres/glTF/IridescenceDielectricSpheres.gltf",
"IridescenceLamp/glTF/IridescenceLamp.gltf",
"IridescenceMetallicSpheres/glTF/IridescenceMetallicSpheres.gltf",
"IridescenceSuzanne/glTF/IridescenceSuzanne.gltf",
"IridescentDishWithOlives/glTF/IridescentDishWithOlives.gltf",
"Lantern/glTF/Lantern.gltf",
"Lantern/glTF-Draco/Lantern.gltf",
"Lantern/glTF-Quantized/Lantern.gltf",
"LightsPunctualLamp/glTF/LightsPunctualLamp.gltf",
// "LightVisibility/glTF/LightVisibility.gltf", // KHR_animation_pointer
"MandarinOrange/glTF/MandarinOrange.gltf",
"MaterialsVariantsShoe/glTF/MaterialsVariantsShoe.gltf",
"MeshPrimitiveModes/glTF/MeshPrimitiveModes.gltf",
"MeshoptCubeTest/glTF/MeshoptCubeTest.gltf",
"MetalRoughSpheres/glTF/MetalRoughSpheres.gltf",
"MetalRoughSpheres/glTF-Embedded/MetalRoughSpheres.gltf",
"MetalRoughSpheresNoTextures/glTF/MetalRoughSpheresNoTextures.gltf",
"MorphPrimitivesTest/glTF/MorphPrimitivesTest.gltf",
"MorphPrimitivesTest/glTF-Draco/MorphPrimitivesTest.gltf",
"MorphStressTest/glTF/MorphStressTest.gltf",
"MosquitoInAmber/glTF/MosquitoInAmber.gltf",
"MultiUVTest/glTF/MultiUVTest.gltf",
"MultiUVTest/glTF-Embedded/MultiUVTest.gltf",
"MultipleScenes/glTF/MultipleScenes.gltf",
"MultipleScenes/glTF-Embedded/MultipleScenes.gltf",
"NegativeScaleTest/glTF/NegativeScaleTest.gltf",
"NodePerformanceTest/glTF/NodePerformanceTest.gltf",
"NormalTangentMirrorTest/glTF/NormalTangentMirrorTest.gltf",
"NormalTangentTest/glTF/NormalTangentTest.gltf",
"OrientationTest/glTF/OrientationTest.gltf",
"OrientationTest/glTF-Embedded/OrientationTest.gltf",
"PlaysetLightTest/glTF/PlaysetLightTest.gltf",
"PointLightIntensityTest/glTF/PointLightIntensityTest.gltf",
"PotOfCoals/glTF/PotOfCoals.gltf",
// "PotOfCoalsAnimationPointer/glTF/PotOfCoalsAnimationPointer.gltf", // KHR_animation_pointer
"PrimitiveModeNormalsTest/glTF/PrimitiveModeNormalsTest.gltf",
"RecursiveSkeletons/glTF/RecursiveSkeletons.gltf",
"RiggedFigure/glTF/RiggedFigure.gltf",
"RiggedFigure/glTF-Draco/RiggedFigure.gltf",
"RiggedFigure/glTF-Embedded/RiggedFigure.gltf",
"RiggedSimple/glTF/RiggedSimple.gltf",
"RiggedSimple/glTF-Draco/RiggedSimple.gltf",
"RiggedSimple/glTF-Embedded/RiggedSimple.gltf",
"ScatteringSkull/glTF/ScatteringSkull.gltf",
"SciFiHelmet/glTF/SciFiHelmet.gltf",
"SheenChair/glTF/SheenChair.gltf",
"SheenCloth/glTF/SheenCloth.gltf",
"SheenTestGrid/glTF/SheenTestGrid.gltf",
// "SheenWoodLeatherSofa/glTF/SheenWoodLeatherSofa.gltf", // EXT_texture_webp
"SimpleInstancing/glTF/SimpleInstancing.gltf",
"SimpleMaterial/glTF/SimpleMaterial.gltf",
"SimpleMaterial/glTF-Embedded/SimpleMaterial.gltf",
"SimpleMeshes/glTF/SimpleMeshes.gltf",
"SimpleMeshes/glTF-Embedded/SimpleMeshes.gltf",
"SimpleSkin/glTF/SimpleSkin.gltf",
"SimpleSkin/glTF-Embedded/SimpleSkin.gltf",
"SimpleSparseAccessor/glTF/SimpleSparseAccessor.gltf",
"SimpleSparseAccessor/glTF-Embedded/SimpleSparseAccessor.gltf",
"SimpleTexture/glTF/SimpleTexture.gltf",
"SimpleTexture/glTF-Embedded/SimpleTexture.gltf",
"SpecGlossVsMetalRough/glTF/SpecGlossVsMetalRough.gltf",
"SpecularSilkPouf/glTF/SpecularSilkPouf.gltf",
"SpecularTest/glTF/SpecularTest.gltf",
"Sponza/glTF/Sponza.gltf",
"StainedGlassLamp/glTF/StainedGlassLamp.gltf",
"StainedGlassLamp/glTF-JPG-PNG/StainedGlassLamp.gltf",
// "StainedGlassLamp/glTF-KTX-BasisU/StainedGlassLamp.gltf", // KHR_texture_basisu
"SunglassesKhronos/glTF/SunglassesKhronos.gltf",
"SunglassesKhronos/glTF-Draco/SunglassesKhronos.gltf",
"Suzanne/glTF/Suzanne.gltf",
"TextureCoordinateTest/glTF/TextureCoordinateTest.gltf",
"TextureCoordinateTest/glTF-Embedded/TextureCoordinateTest.gltf",
"TextureEncodingTest/glTF/TextureEncodingTest.gltf",
"TextureLinearInterpolationTest/glTF/TextureLinearInterpolationTest.gltf",
"TextureSettingsTest/glTF/TextureSettingsTest.gltf",
"TextureSettingsTest/glTF-Embedded/TextureSettingsTest.gltf",
"TextureTransformMultiTest/glTF/TextureTransformMultiTest.gltf",
"TextureTransformTest/glTF/TextureTransformTest.gltf",
"ToyCar/glTF/ToyCar.gltf",
"TransmissionOrderTest/glTF/TransmissionOrderTest.gltf",
"TransmissionRoughnessTest/glTF/TransmissionRoughnessTest.gltf",
"TransmissionTest/glTF/TransmissionTest.gltf",
"TransmissionThinwallTestGrid/glTF/TransmissionThinwallTestGrid.gltf",
"Triangle/glTF/Triangle.gltf",
"Triangle/glTF-Embedded/Triangle.gltf",
"TriangleWithoutIndices/glTF/TriangleWithoutIndices.gltf",
"TriangleWithoutIndices/glTF-Embedded/TriangleWithoutIndices.gltf",
"TwoSidedPlane/glTF/TwoSidedPlane.gltf",
"USDShaderBallForGltf/glTF/USDShaderBallForGltf.gltf",
"Unicode❤♻Test/glTF/Unicode❤♻Test.gltf",
"UnlitTest/glTF/UnlitTest.gltf",
"VertexColorTest/glTF/VertexColorTest.gltf",
"VertexColorTest/glTF-Embedded/VertexColorTest.gltf",
"VirtualCity/glTF/VirtualCity.gltf",
"VirtualCity/glTF-Draco/VirtualCity.gltf",
"VirtualCity/glTF-Embedded/VirtualCity.gltf",
"WaterBottle/glTF/WaterBottle.gltf",
"WaterBottle/glTF-Draco/WaterBottle.gltf",
"XmpMetadataRoundedCube/glTF/XmpMetadataRoundedCube.gltf",
];

#[cfg(target_os = "windows")]
const PATHS: &[&str] = &[
"ABeautifulGame\\glTF\\ABeautifulGame.gltf",
"AlphaBlendModeTest\\glTF\\AlphaBlendModeTest.gltf",
"AnimatedColorsCube\\glTF\\AnimatedColorsCube.gltf",
"AnimatedCube\\glTF\\AnimatedCube.gltf",
"AnimatedMorphCube\\glTF\\AnimatedMorphCube.gltf",
"AnimatedMorphCube\\glTF-Quantized\\AnimatedMorphCube.gltf",
"AnimatedTriangle\\glTF\\AnimatedTriangle.gltf",
"AnimationPointerUVs\\glTF\\AnimationPointerUVs.gltf",
"AnisotropyBarnLamp\\glTF\\AnisotropyBarnLamp.gltf",
"AnisotropyBarnLamp\\glTF-KTX-BasisU\\AnisotropyBarnLamp.gltf",
"AnisotropyDiscTest\\glTF\\AnisotropyDiscTest.gltf",
"AnisotropyRotationTest\\glTF\\AnisotropyRotationTest.gltf",
"AnisotropyStrengthTest\\glTF\\AnisotropyStrengthTest.gltf",
"AntiqueCamera\\glTF\\AntiqueCamera.gltf",
"AttenuationTest\\glTF\\AttenuationTest.gltf",
"Avocado\\glTF\\Avocado.gltf",
"Avocado\\glTF-Draco\\Avocado.gltf",
"Avocado\\glTF-Quantized\\Avocado.gltf",
"BarramundiFish\\glTF\\BarramundiFish.gltf",
"BarramundiFish\\glTF-Draco\\BarramundiFish.gltf",
"BoomBox\\glTF\\BoomBox.gltf",
"BoomBox\\glTF-Draco\\BoomBox.gltf",
"BoomBoxWithAxes\\glTF\\BoomBoxWithAxes.gltf",
"Box\\glTF\\Box.gltf",
"Box\\glTF-Draco\\Box.gltf",
"Box\\glTF-Embedded\\Box.gltf",
"Box With Spaces\\glTF\\Box With Spaces.gltf",
"BoxAnimated\\glTF\\BoxAnimated.gltf",
"BoxAnimated\\glTF-Embedded\\BoxAnimated.gltf",
"BoxInterleaved\\glTF\\BoxInterleaved.gltf",
"BoxInterleaved\\glTF-Embedded\\BoxInterleaved.gltf",
"BoxTextured\\glTF\\BoxTextured.gltf",
"BoxTextured\\glTF-Embedded\\BoxTextured.gltf",
"BoxTexturedNonPowerOfTwo\\glTF\\BoxTexturedNonPowerOfTwo.gltf",
"BoxTexturedNonPowerOfTwo\\glTF-Embedded\\BoxTexturedNonPowerOfTwo.gltf",
"BoxVertexColors\\glTF\\BoxVertexColors.gltf",
"BoxVertexColors\\glTF-Embedded\\BoxVertexColors.gltf",
"BrainStem\\glTF\\BrainStem.gltf",
"BrainStem\\glTF-Draco\\BrainStem.gltf",
"BrainStem\\glTF-Embedded\\BrainStem.gltf",
"BrainStem\\glTF-Meshopt\\BrainStem.gltf",
"BrainStem\\glTF-Meshopt-EXT\\BrainStem.gltf",
"Cameras\\glTF\\Cameras.gltf",
"Cameras\\glTF-Embedded\\Cameras.gltf",
"CarConcept\\glTF\\CarConcept.gltf",
"CarConcept\\glTF-JPG\\CarConcept.gltf",
"CarConcept\\glTF-KTX-BasisU-Draco\\CarConcept.gltf",
"CarConcept\\glTF-WEBP\\CarConcept.gltf",
"CarbonFibre\\glTF\\CarbonFibre.gltf",
"CesiumMan\\glTF\\CesiumMan.gltf",
"CesiumMan\\glTF-Draco\\CesiumMan.gltf",
"CesiumMan\\glTF-Embedded\\CesiumMan.gltf",
"CesiumMilkTruck\\glTF\\CesiumMilkTruck.gltf",
"CesiumMilkTruck\\glTF-Draco\\CesiumMilkTruck.gltf",
"CesiumMilkTruck\\glTF-Embedded\\CesiumMilkTruck.gltf",
"ChairDamaskPurplegold\\glTF\\ChairDamaskPurplegold.gltf",
"ChronographWatch\\glTF\\ChronographWatch.gltf",
"ChronographWatch\\glTF-KTX-BasisU\\ChronographWatch.gltf",
"ChronographWatch\\glTF-WEBP\\ChronographWatch.gltf",
"ClearCoatCarPaint\\glTF\\ClearCoatCarPaint.gltf",
"ClearCoatTest\\glTF\\ClearCoatTest.gltf",
"ClearcoatWicker\\glTF\\ClearcoatWicker.gltf",
"CommercialRefrigerator\\glTF\\CommercialRefrigerator.gltf",
"CompareAlphaCoverage\\glTF\\CompareAlphaCoverage.gltf",
"CompareAmbientOcclusion\\glTF\\CompareAmbientOcclusion.gltf",
"CompareAnisotropy\\glTF\\CompareAnisotropy.gltf",
"CompareBaseColor\\glTF\\CompareBaseColor.gltf",
"CompareClearcoat\\glTF\\CompareClearcoat.gltf",
"CompareDispersion\\glTF\\CompareDispersion.gltf",
"CompareEmissiveStrength\\glTF\\CompareEmissiveStrength.gltf",
"CompareIor\\glTF\\CompareIor.gltf",
"CompareIridescence\\glTF\\CompareIridescence.gltf",
"CompareMetallic\\glTF\\CompareMetallic.gltf",
"CompareNormal\\glTF\\CompareNormal.gltf",
"CompareRoughness\\glTF\\CompareRoughness.gltf",
"CompareSheen\\glTF\\CompareSheen.gltf",
"CompareSpecular\\glTF\\CompareSpecular.gltf",
"CompareTransmission\\glTF\\CompareTransmission.gltf",
"CompareVolume\\glTF\\CompareVolume.gltf",
"Corset\\glTF\\Corset.gltf",
"Corset\\glTF-Draco\\Corset.gltf",
"Cube\\glTF\\Cube.gltf",
"CubeVisibility\\glTF\\CubeVisibility.gltf",
"DamagedHelmet\\glTF\\DamagedHelmet.gltf",
"DamagedHelmet\\glTF-Embedded\\DamagedHelmet.gltf",
"DiffuseTransmissionPlant\\glTF\\DiffuseTransmissionPlant.gltf",
"DiffuseTransmissionTeacup\\glTF\\DiffuseTransmissionTeacup.gltf",
"DiffuseTransmissionTest\\glTF\\DiffuseTransmissionTest.gltf",
"DirectionalLight\\glTF\\DirectionalLight.gltf",
"DispersionTest\\glTF\\DispersionTest.gltf",
"DragonAttenuation\\glTF\\DragonAttenuation.gltf",
"DragonAttenuation\\glTF-Meshopt\\DragonAttenuation.gltf",
"DragonAttenuation\\glTF-Meshopt-EXT\\DragonAttenuation.gltf",
"DragonDispersion\\glTF\\DragonDispersion.gltf",
"Duck\\glTF\\Duck.gltf",
"Duck\\glTF-Draco\\Duck.gltf",
"Duck\\glTF-Embedded\\Duck.gltf",
"Duck\\glTF-Quantized\\Duck.gltf",
"EmissiveStrengthTest\\glTF\\EmissiveStrengthTest.gltf",
"EnvironmentTest\\glTF\\EnvironmentTest.gltf",
"FlightHelmet\\glTF\\FlightHelmet.gltf",
"Fox\\glTF\\Fox.gltf",
"GlamVelvetSofa\\glTF\\GlamVelvetSofa.gltf",
"GlassBrokenWindow\\glTF\\GlassBrokenWindow.gltf",
"GlassHurricaneCandleHolder\\glTF\\GlassHurricaneCandleHolder.gltf",
"GlassVaseFlowers\\glTF\\GlassVaseFlowers.gltf",
"IORTestGrid\\glTF\\IORTestGrid.gltf",
"InterpolationTest\\glTF\\InterpolationTest.gltf",
"IridescenceAbalone\\glTF\\IridescenceAbalone.gltf",
"IridescenceDielectricSpheres\\glTF\\IridescenceDielectricSpheres.gltf",
"IridescenceLamp\\glTF\\IridescenceLamp.gltf",
"IridescenceMetallicSpheres\\glTF\\IridescenceMetallicSpheres.gltf",
"IridescenceSuzanne\\glTF\\IridescenceSuzanne.gltf",
"IridescentDishWithOlives\\glTF\\IridescentDishWithOlives.gltf",
"Lantern\\glTF\\Lantern.gltf",
"Lantern\\glTF-Draco\\Lantern.gltf",
"Lantern\\glTF-Quantized\\Lantern.gltf",
"LightsPunctualLamp\\glTF\\LightsPunctualLamp.gltf",
"LightVisibility\\glTF\\LightVisibility.gltf",
"MandarinOrange\\glTF\\MandarinOrange.gltf",
"MaterialsVariantsShoe\\glTF\\MaterialsVariantsShoe.gltf",
"MeshPrimitiveModes\\glTF\\MeshPrimitiveModes.gltf",
"MeshoptCubeTest\\glTF\\MeshoptCubeTest.gltf",
"MetalRoughSpheres\\glTF\\MetalRoughSpheres.gltf",
"MetalRoughSpheres\\glTF-Embedded\\MetalRoughSpheres.gltf",
"MetalRoughSpheresNoTextures\\glTF\\MetalRoughSpheresNoTextures.gltf",
"MorphPrimitivesTest\\glTF\\MorphPrimitivesTest.gltf",
"MorphPrimitivesTest\\glTF-Draco\\MorphPrimitivesTest.gltf",
"MorphStressTest\\glTF\\MorphStressTest.gltf",
"MosquitoInAmber\\glTF\\MosquitoInAmber.gltf",
"MultiUVTest\\glTF\\MultiUVTest.gltf",
"MultiUVTest\\glTF-Embedded\\MultiUVTest.gltf",
"MultipleScenes\\glTF\\MultipleScenes.gltf",
"MultipleScenes\\glTF-Embedded\\MultipleScenes.gltf",
"NegativeScaleTest\\glTF\\NegativeScaleTest.gltf",
"NodePerformanceTest\\glTF\\NodePerformanceTest.gltf",
"NormalTangentMirrorTest\\glTF\\NormalTangentMirrorTest.gltf",
"NormalTangentTest\\glTF\\NormalTangentTest.gltf",
"OrientationTest\\glTF\\OrientationTest.gltf",
"OrientationTest\\glTF-Embedded\\OrientationTest.gltf",
"PlaysetLightTest\\glTF\\PlaysetLightTest.gltf",
"PointLightIntensityTest\\glTF\\PointLightIntensityTest.gltf",
"PotOfCoals\\glTF\\PotOfCoals.gltf",
"PotOfCoalsAnimationPointer\\glTF\\PotOfCoalsAnimationPointer.gltf",
"PrimitiveModeNormalsTest\\glTF\\PrimitiveModeNormalsTest.gltf",
"RecursiveSkeletons\\glTF\\RecursiveSkeletons.gltf",
"RiggedFigure\\glTF\\RiggedFigure.gltf",
"RiggedFigure\\glTF-Draco\\RiggedFigure.gltf",
"RiggedFigure\\glTF-Embedded\\RiggedFigure.gltf",
"RiggedSimple\\glTF\\RiggedSimple.gltf",
"RiggedSimple\\glTF-Draco\\RiggedSimple.gltf",
"RiggedSimple\\glTF-Embedded\\RiggedSimple.gltf",
"ScatteringSkull\\glTF\\ScatteringSkull.gltf",
"SciFiHelmet\\glTF\\SciFiHelmet.gltf",
"SheenChair\\glTF\\SheenChair.gltf",
"SheenCloth\\glTF\\SheenCloth.gltf",
"SheenTestGrid\\glTF\\SheenTestGrid.gltf",
"SheenWoodLeatherSofa\\glTF\\SheenWoodLeatherSofa.gltf",
"SimpleInstancing\\glTF\\SimpleInstancing.gltf",
"SimpleMaterial\\glTF\\SimpleMaterial.gltf",
"SimpleMaterial\\glTF-Embedded\\SimpleMaterial.gltf",
"SimpleMeshes\\glTF\\SimpleMeshes.gltf",
"SimpleMeshes\\glTF-Embedded\\SimpleMeshes.gltf",
"SimpleSkin\\glTF\\SimpleSkin.gltf",
"SimpleSkin\\glTF-Embedded\\SimpleSkin.gltf",
"SimpleSparseAccessor\\glTF\\SimpleSparseAccessor.gltf",
"SimpleSparseAccessor\\glTF-Embedded\\SimpleSparseAccessor.gltf",
"SimpleTexture\\glTF\\SimpleTexture.gltf",
"SimpleTexture\\glTF-Embedded\\SimpleTexture.gltf",
"SpecGlossVsMetalRough\\glTF\\SpecGlossVsMetalRough.gltf",
"SpecularSilkPouf\\glTF\\SpecularSilkPouf.gltf",
"SpecularTest\\glTF\\SpecularTest.gltf",
"Sponza\\glTF\\Sponza.gltf",
"StainedGlassLamp\\glTF\\StainedGlassLamp.gltf",
"StainedGlassLamp\\glTF-JPG-PNG\\StainedGlassLamp.gltf",
"StainedGlassLamp\\glTF-KTX-BasisU\\StainedGlassLamp.gltf",
"SunglassesKhronos\\glTF\\SunglassesKhronos.gltf",
"SunglassesKhronos\\glTF-Draco\\SunglassesKhronos.gltf",
"Suzanne\\glTF\\Suzanne.gltf",
"TextureCoordinateTest\\glTF\\TextureCoordinateTest.gltf",
"TextureCoordinateTest\\glTF-Embedded\\TextureCoordinateTest.gltf",
"TextureEncodingTest\\glTF\\TextureEncodingTest.gltf",
"TextureLinearInterpolationTest\\glTF\\TextureLinearInterpolationTest.gltf",
"TextureSettingsTest\\glTF\\TextureSettingsTest.gltf",
"TextureSettingsTest\\glTF-Embedded\\TextureSettingsTest.gltf",
"TextureTransformMultiTest\\glTF\\TextureTransformMultiTest.gltf",
"TextureTransformTest\\glTF\\TextureTransformTest.gltf",
"ToyCar\\glTF\\ToyCar.gltf",
"TransmissionOrderTest\\glTF\\TransmissionOrderTest.gltf",
"TransmissionRoughnessTest\\glTF\\TransmissionRoughnessTest.gltf",
"TransmissionTest\\glTF\\TransmissionTest.gltf",
"TransmissionThinwallTestGrid\\glTF\\TransmissionThinwallTestGrid.gltf",
"Triangle\\glTF\\Triangle.gltf",
"Triangle\\glTF-Embedded\\Triangle.gltf",
"TriangleWithoutIndices\\glTF\\TriangleWithoutIndices.gltf",
"TriangleWithoutIndices\\glTF-Embedded\\TriangleWithoutIndices.gltf",
"TwoSidedPlane\\glTF\\TwoSidedPlane.gltf",
"USDShaderBallForGltf\\glTF\\USDShaderBallForGltf.gltf",
"Unicode❤♻Test\\glTF\\Unicode❤♻Test.gltf",
"UnlitTest\\glTF\\UnlitTest.gltf",
"VertexColorTest\\glTF\\VertexColorTest.gltf",
"VertexColorTest\\glTF-Embedded\\VertexColorTest.gltf",
"VirtualCity\\glTF\\VirtualCity.gltf",
"VirtualCity\\glTF-Draco\\VirtualCity.gltf",
"VirtualCity\\glTF-Embedded\\VirtualCity.gltf",
"WaterBottle\\glTF\\WaterBottle.gltf",
"WaterBottle\\glTF-Draco\\WaterBottle.gltf",
"XmpMetadataRoundedCube\\glTF\\XmpMetadataRoundedCube.gltf",
];

#[test]
fn parse_test() {
  minimal_parse_test();
  // let mut prefix = std::env::var("GLTF_PREFIX").unwrap();
  // let path = PathBuf::from(prefix);
  // PATHS.iter().for_each(|&f| {
  //   let p_str = String::from(f);
  //   let p = PathBuf::from(p_str);
  //   let joined_p = path.join(p);
  //   let parsed = GltfLoader::load(&joined_p);
  //   // println!("{:?}", loaded);
  //   // if (loaded.buffers.is_some()) {
  //   //   println!("{:?}", loaded.buffers.unwrap());
  //   // }
  //   if parsed.is_ok() {
  //     let loaded = parsed.unwrap();
  //   }
  //   else {
  //     println!("{}", f);
  //     println!("{}", parsed.unwrap_err());
  //   }
  // });
}

fn minimal_parse_test() {
  let p_str = String::from(".\\assets\\minimal.gltf");
  let p = PathBuf::from(p_str);
  let parsed = GltfDocument::load(&p);
  match parsed {
    Ok(_) => (),
    Err(e) => println!("{}", e.to_string())
  };
}